'use strict';
function openOrderForm(id=null,complement=false){
  if(!can('saveOrder'))throw new Error('Sem permissão para criar pedidos.');
  const old=id?find(orders(),id):null;
  editingOrder={id:complement?null:old?.id,complementarDe:complement?id:null};
  modal(complement?'Pedido complementar':old?'Editar pedido':'Novo pedido',`${notice('Dados demonstrativos. Quantidades em embalagens inteiras (UN); preço e comissão-base preenchidos pela tabela liberada. Ao enviar ao Financeiro, a edição é bloqueada.')}<div class="form-grid">${select('Cliente','clienteId',clients().filter(c=>c.ativo).map(c=>[c.id,c.nomeFantasia]),old?.clienteId||'c1')}${input('Prazo de entrega','prazoEntrega',old?.prazoEntrega||D.day(15),'date',`required min="${D.today()}"`)}${select('Condições comerciais','condicoesComerciais',[['30/60 dias','30/60 dias'],['À vista','À vista'],['28 dias','28 dias']],old?.condicoesComerciais||'30/60 dias')}${input('Vendedor responsável','sellerLabel','', 'text','readonly')}</div><div id="orderLines"></div><div>${btn('+ Adicionar produto','addLine')}</div><div id="orderTotals"></div>${textarea('Observações','observacoes',complement?'Complementar ao '+old.numero:old?.observacoes||'')}`,data=>{
    const result=commit('saveOrder',{...editingOrder,...data,itens:[...document.querySelectorAll('.order-line')].map(row=>({produtoId:row.querySelector('select').value,quantidade:row.querySelector('input').value}))});route='pedidos';selectedId=result;
  },'Salvar rascunho');
  const items=old?.itens||[{produtoId:'p1',quantidade:20}];items.forEach(i=>addOrderLine(i));updateOrderTotals();
}
function addOrderLine(i={}){
 const c=find(state.clientes,$('[name="clienteId"]').value);
 const eligible=state.produtos.filter(p=>p.status==='ativo'&&p.precoLiberado&&p.tabela===c.tabela&&p.formulaId&&find(state.formulas,p.formulaId).status==='ativa');
 const n=document.querySelectorAll('.order-line').length+1;
 $('#orderLines').insertAdjacentHTML('beforeend',`<div class="order-line">${select(`Produto ${n}`,'product',eligible.map(p=>[p.id,`${p.codigo} · ${p.nome}`]),i.produtoId||eligible[0]?.id)}${input(`Quantidade ${n}`,'quantity',i.quantidade||1,'number','min="1" step="1" required')}<div class="line-amount calculated"></div><button type="button" class="ghost-btn remove-line" data-action="removeLine" aria-label="Remover item ${n}">×</button></div>`);
 updateOrderTotals();
}
function updateOrderTotals(){
 if(!$('#orderLines'))return;let total=0,comm=0,kg=0;
 const c=find(state.clientes,$('[name="clienteId"]').value);$('[name="sellerLabel"]').value=find(state.usuarios,c.vendedorId).nome;
 document.querySelectorAll('.order-line').forEach(row=>{const p=state.produtos.find(p=>p.id===row.querySelector('select').value),q=Number(row.querySelector('input').value)||0;if(!p){row.querySelector('.line-amount').textContent='Sem preço liberado';return;}total+=q*p.precoCentavos;comm+=Math.round(q*p.precoCentavos*p.comissaoBps/10000);kg+=q*p.pesoKg;row.querySelector('.line-amount').innerHTML=`${money(q*p.precoCentavos)}<small class="muted"> · ${p.comissaoBps/100}%</small>`;});
 $('#orderTotals').innerHTML=`<div class="summary-total"><div><span class="muted">Total do pedido</span><strong>${money(total)}</strong></div><div>Comissão: <b>${money(comm)}</b><p class="muted small">Peso de produção: ${qty(kg)} kg</p></div></div>`;
}
function productionForm(id){
 const op=find(state.ordens,id),remaining=op.quantidadePrevista-op.quantidadeProduzida;
 modal('Apontar produção · '+op.numero,`${notice('Informe a produção deste apontamento. A OP permanece aberta até completar a quantidade prevista. Perdas e sobras aumentam o consumo de insumos.')}<div class="form-grid">${input('Quantidade produzida (UN)','quantidade',remaining,'number',`required min="1" max="${remaining}" step="1"`)}${input('Validade do lote final','validade',D.day(180),'date',`required min="${D.today()}"`)}${input('Perdas (kg)','perdasKg',0,'number','required min="0" step="0.001"')}${input('Sobras segregadas (kg)','sobrasKg',0,'number','required min="0" step="0.001"')}</div><p class="muted small">Validade de 180 dias é apenas exemplo, confirme a regra do produto. Sobras ficam segregadas, sem venda ou reaproveitamento automático.</p><div id="consumptionSummary"></div><div>${btn('Sugerir lotes por validade','suggestLots',id)}</div><div id="consumptionRows"></div>${textarea('Observações (obrigatórias se houver perdas ou sobras)','observacoes')}`,data=>commit('reportProduction',{id,...data,consumos:[...document.querySelectorAll('[data-lot-consumption]')].map(el=>({loteId:el.dataset.lotConsumption,quantidade:el.value}))}),'Registrar apontamento');
 $('#dialogBody').dataset.op=id;drawConsumption(id);
}
function drawConsumption(id){
 const op=find(state.ordens,id),d=formData(),kg=Number(d.quantidade)*op.pesoKg+Number(d.perdasKg)+Number(d.sobrasKg);
 const needs=D.requirements(op,Number.isFinite(kg)&&kg>=0?kg:0),suggested=D.suggestConsumption(state,op,Number.isFinite(kg)&&kg>=0?kg:0);
 $('#consumptionSummary').innerHTML=notice(`Massa do apontamento: <b>${qty(kg)} kg</b> = produto embalado + perdas + sobras. Confira os lotes antes de confirmar.`);
 $('#consumptionRows').innerHTML=needs.map(r=>{const lots=D.eligibleLots(state,r.ingredienteId),available=lots.reduce((n,l)=>n+l.saldo,0);return panel(esc(find(state.ingredientes,r.ingredienteId).nome),`<p class="small">Necessário: <b>${qty(r.quantidade)} kg</b> · disponível: ${qty(available)} kg ${available<r.quantidade?badge('Insuficiente'):''}</p>${table(['Lote','Fornecedor','Validade','Saldo','Consumir (kg)'],lots.map(l=>[esc(l.codigo),esc(find(state.fornecedores,l.fornecedorId).nome),fmtDate(l.validade),qty(l.saldo),`<input class="consumption-input" aria-label="Consumo ${esc(l.codigo)}" data-lot-consumption="${l.id}" type="number" min="0" max="${l.saldo}" step="0.001" value="${suggested.find(c=>c.loteId===l.id)?.quantidade||0}">`]))}`);}).join('');
}
function traceBody(id){
 const lot=find(state.lotes,id), isInput=lot.tipo==='ingrediente';
 const matches=state.ordens.flatMap(op=>op.apontamentos.filter(a=>isInput?a.consumos.some(c=>c.loteId===id):a.loteId===id).map(a=>({op,a})));
 return `${fields([['Lote',esc(lot.codigo)],['Saldo',`${qty(lot.saldo)} ${isInput?'kg':'UN'}`],['Validade',fmtDate(lot.validade)],['Situação',badge(lot.status)]])}${matches.length?matches.map(({op,a})=>{const order=find(state.pedidos,op.pedidoId),final=find(state.lotes,a.loteId);return panel(`${esc(op.numero)} → ${esc(final.codigo)}`,`${fields([['Produto',esc(op.produtoNome)],['Fórmula preservada',`${esc(op.formula.codigo)} · v${op.formula.versao}`],['Pedido / cliente',`${esc(order.numero)} · ${esc(order.clienteNome)}`],['Apontamento',`${a.quantidade} UN · ${fmtTime(a.data)}`],['Responsável',esc(a.usuario)],['Despacho',order.despacho?`${esc(order.despacho.transportadora)} · ${esc(order.despacho.rastreamento)}`:'Ainda não despachado']])}<h4>Origens consumidas</h4>${table(['Lote de entrada','Ingrediente','Fornecedor','Validade','Consumo'],a.consumos.map(c=>{const l=find(state.lotes,c.loteId);return [esc(l.codigo),esc(find(state.ingredientes,c.ingredienteId).nome),esc(find(state.fornecedores,l.fornecedorId).nome),fmtDate(l.validade),`${qty(c.quantidade)} kg`];}))}${costs()?`<p>Custo dos insumos: ${money(a.custoInsumosCentavos)} (inclui consumo relativo às perdas e sobras; embalagem e despesas não incluídas).</p>`:''}<h4>Inspeções do lote final</h4>${table(['Resultado','Responsável','Data','Observações / laudo'],final.inspecoes.map(i=>[badge(i.resultado),esc(i.usuario),fmtTime(i.data),`${esc(i.observacoes)}<small>${esc(i.laudo||'Sem laudo informado')}</small>`]))}`);}).join(''):notice('Este lote ainda não participou de uma produção. A origem será ligada à OP e ao cliente no apontamento.')}`;
}
function openAction(a,id){
 if(a in D.permissions && !can(a))throw new Error('Seu perfil não permite esta ação.');
 if(a==='saveOrder')return openOrderForm(id||null);
 if(a==='complement')return openOrderForm(id,true);
 if(a==='addLine')return addOrderLine();
 if(a==='suggestLots')return drawConsumption(id);
 if(a==='reportProduction')return productionForm(id);
 if(a==='analyze'){
  const o=find(orders(),id),c=find(state.clientes,o.clienteId),cr=D.credit(state,o);
  return modal('Análise financeira · '+o.numero,`${fields([['Cliente',esc(c.nomeFantasia)],['Situação',badge(c.situacaoFinanceira)],['Limite',money(c.limiteCentavos)],['Exposição anterior',money(cr.exposure)],['Este pedido',money(D.orderTotal(o))],['Crédito após pedido',money(c.limiteCentavos-cr.projected)]])}${cr.warning?notice('Há restrição ou crédito insuficiente. Liberação exige decisão com restrição e justificativa.','warn'):notice('O crédito disponível comporta este pedido.')}${select('Decisão','decisao',[['liberado','Liberado'],['liberadoComRestricao','Liberado com restrição'],['bloqueado','Bloqueado']],cr.warning?'liberadoComRestricao':'liberado')}${textarea('Justificativa (obrigatória em restrição ou bloqueio)','justificativa')}`,d=>commit(a,{id,...d}),'Registrar análise');
 }
 if(a==='inspect'){const l=find(state.lotes,id);return modal('Inspecionar '+l.codigo,notice('Resultado vinculado ao lote e responsável. Reprovação bloqueia faturamento; retrabalho não é simulado.')+select('Resultado','decisao',[['aprovado','Aprovado'],['reprovado','Reprovado']])+textarea('Observações / motivo de reprovação','observacoes')+input('Referência do laudo (opcional, sem upload)','laudo'),d=>commit(a,{id,...d}),'Registrar inspeção');}
 if(a==='bill')return modal('Registrar faturamento interno',notice('Não emite NF-e e não envia informação a serviços fiscais.')+input('Referência interna','referencia','FAT-DEMO-'+find(state.pedidos,id).numero,'text','required'),d=>commit(a,{id,...d}),'Registrar faturamento');
 if(a==='dispatch')return modal('Registrar frete e despacho',notice('Dados informativos. Comprovante é uma referência textual, não um arquivo enviado.')+`<div class="form-grid">${input('Transportadora','transportadora','','text','required')}${input('Valor do frete (R$)','valor',0,'number','required min="0" step="0.01"')}${input('Data de saída','dataSaida',D.today(),'date',`required max="${D.today()}"`)}${input('Prazo de entrega do frete','prazo',D.day(5),'date','required')}${input('Código de rastreamento','rastreamento','','text','required')}${input('Referência do comprovante','comprovante','','text','required')}</div>`,d=>commit(a,{id,...d}),'Confirmar despacho');
 if(a==='receiveLot')return modal('Receber matéria-prima',`<div class="form-grid">${select('Ingrediente','ingredienteId',state.ingredientes.map(i=>[i.id,i.nome]))}${select('Fornecedor','fornecedorId',state.fornecedores.map(i=>[i.id,i.nome]))}${input('Código único do lote','codigo','','text','required')}${input('Quantidade (kg)','quantidade',100,'number','min="0.001" step="0.001" required')}${input('Fabricação','fabricacao',D.today(),'date','required')}${input('Validade','validade',D.day(180),'date','required')}</div>`,d=>commit(a,d),'Registrar entrada');
 if(a==='adjustLot')return modal('Ajustar '+find(state.lotes,id).codigo,input('Novo saldo (kg)','saldo',find(state.lotes,id).saldo,'number','required min="0" step="0.001"')+textarea('Justificativa do ajuste','justificativa','',true),d=>commit(a,{id,...d}),'Registrar ajuste');
 if(a==='saveClient')return modal('Novo cliente de demonstração',notice('Use apenas dados fictícios. CNPJ deve ter dígitos verificadores válidos e ser único. Limite inicial: zero.')+`<div class="form-grid">${input('Razão social','razaoSocial','','text','required')}${input('Nome fantasia','nomeFantasia','','text','required')}${input('CNPJ','cnpj','','text','required')}${input('Inscrição estadual / ISENTO','inscricaoEstadual','ISENTO','text','required')}${input('Endereço completo','endereco','','text','required')}${input('Contato (nome, e-mail ou telefone)','contato','','text','required')}</div>`,d=>commit(a,d),'Cadastrar cliente');
 if(a==='createVersion'){const f=find(state.formulas,id);return modal('Nova versão · '+f.codigo,notice('A versão atual será preservada. A nova começa em desenvolvimento. Nesta simulação, a soma dos insumos deve corresponder ao rendimento.')+`<div class="form-grid">${input('Rendimento (kg)','rendimento',f.rendimento,'number','required min="0.001" step="0.001"')}${f.itens.map(i=>input(esc(find(state.ingredientes,i.ingredienteId).nome)+' (kg)',i.ingredienteId,i.quantidade,'number','required min="0" step="0.001"')).join('')}${textarea('Justificativa da versão','justificativa','',true)}</div>`,d=>commit(a,{id,...d,itens:f.itens.map(i=>({ingredienteId:i.ingredienteId,quantidade:d[i.ingredienteId]}))}),'Criar versão');}
 if(a==='activateVersion')return modal('Ativar versão',notice('Produtos vinculados passam a usar esta versão para novos pedidos. Preços precisarão de nova liberação. Pedidos e OPs existentes preservam sua composição.')+textarea('Justificativa de ativação','justificativa','',true),d=>commit(a,{id,...d}),'Ativar versão');
 if(a==='releasePrice'){const p=find(state.produtos,id);modal('Simular preço · '+p.nome,input('Margem sobre venda (%)','margem',35,'number','required min="0" max="94.99" step="0.01"')+'<div id="priceResult"></div>'+notice('Libera o novo preço somente para pedidos criados ou revisados depois. Histórico dos pedidos existentes não muda.'),d=>commit(a,{id,...d}),'Liberar preço');$('#dialogBody').dataset.product=id;updatePrice();return;}
 if(a==='trace'){if(!['administrador','producao','qualidade','estoque'].includes(user.perfil))throw new Error('Rastreabilidade restrita à operação.');return modal('Rastreabilidade · '+find(state.lotes,id).codigo,traceBody(id));}
 if(a==='viewSheet'){if(!technical())throw new Error('Documento da OP restrito.');const x=find(state.ordens,id),d=x.documentoOp;return modal('Consultar doc. OP · '+x.numero,`<div class="doc-tabs"><button type="button" class="ghost-btn active" data-doc-tab="demonstracao">Ficha de demonstração</button><button type="button" class="ghost-btn" data-doc-tab="etiqueta">Etiqueta</button></div><section data-doc-panel="demonstracao">${fields([['Documento',esc(d.numero)],['Produto',esc(x.produtoNome)],['Fórmula / versão',`${esc(x.formula.codigo)} · v${x.formula.versao}`],['Emissão',fmtTime(d.data)],['Responsável',esc(d.usuario)],['Quantidade',`${x.quantidadePrevista} UN · ${qty(x.quantidadePrevista*x.pesoKg)} kg`]])}${table(['Ingrediente','Quantidade'],d.necessidades.map(r=>[esc(find(state.ingredientes,r.ingredienteId).nome),`${qty(r.quantidade)} kg`]))}${btn('Imprimir / salvar em PDF','printDoc',id,true)}</section><section data-doc-panel="etiqueta" hidden>${x.etiquetas?.length?table(['Modelo','Tamanho','Quantidade','Dados'],x.etiquetas.map(i=>{const e=find(state.etiquetas,i.etiquetaId);return [esc(e.nome),esc(e.tamanho),i.quantidade,esc(e.conteudo)];})):'<p class="muted">Nenhuma etiqueta definida para esta OP.</p>'}${actionButton('Modificar quantidades','editOpLabels',id,true)}${notice('Proposta preliminar: o formato final e a impressão em lote ainda serão validados.','warn')}</section>`);}
 if(a==='editLabel'){const e=find(state.etiquetas,id);return modal('Modificar etiqueta · '+e.tamanho,input('Nome do modelo','nome',e.nome,'text','required')+textarea('Dados que devem constar','conteudo',e.conteudo,true)+textarea('Observações','observacoes',e.observacoes||''),d=>commit('saveLabel',{id,...d}),'Salvar modelo');}
 if(a==='editOpLabels'){const x=find(state.ordens,id),getQty=eid=>x.etiquetas?.find(i=>i.etiquetaId===eid)?.quantidade||0;return modal('Etiquetas da '+x.numero,notice('Quantidades e conteúdo são uma proposta provisória e poderão mudar após o detalhamento.','warn')+`<div class="form-grid">${input('Etiqueta pequena','pequena',getQty('etq1'),'number','required min="0" step="1"')}${input('Etiqueta grande','grande',getQty('etq2'),'number','required min="0" step="1"')}</div>`,d=>commit('saveOpLabels',{id,...d}),'Salvar quantidades');}
 if(a==='printDoc'){window.print();return;}
 if(a==='clientHistory'){if(!allowed('clientes'))throw new Error('Acesso restrito.');const c=find(clients(),id),h=c.historicoFinanceiro||[],late=h.filter(x=>x.diasAtraso>0);return modal('Histórico financeiro · '+c.nomeFantasia,fields([['Status atual',badge(c.situacaoFinanceira)],['Limite vigente',money(c.limiteCentavos)],['Meses com atraso',late.length],['Maior atraso',`${Math.max(0,...late.map(x=>x.diasAtraso))} dias`]])+table(['Mês','Situação da análise','Atraso observado'],h.map(x=>[x.mes.split('-').reverse().join('/'),badge(x.status),x.diasAtraso?`${x.diasAtraso} dias`:'Em dia']))+notice('O histórico apoia a análise humana de limite. A situação atual não deve apagar decisões ou atrasos anteriores.'));}
 if(a==='auditDetails'){if(!allowed('auditoria'))throw new Error('Auditoria restrita.');const event=find(state.auditoria,id);const redact=value=>{if(user.perfil==='administrador')return value;if(!value)return null;return {id:value.id,numero:value.numero,status:value.status,statusAnalise:value.statusAnalise,ativo:value.ativo};};return modal(actionNames[event.acao]||event.acao,notice(user.perfil==='diretor'?'Diretor vê resumo sem fórmulas e custos.':'Snapshot local do registro antes e depois.')+`<div class="grid-2">${panel('Antes',`<pre class="audit-json">${esc(JSON.stringify(redact(event.antes),null,2))}</pre>`)}${panel('Depois',`<pre class="audit-json">${esc(JSON.stringify(redact(event.depois),null,2))}</pre>`)}</div>`);}
 if(a==='exportCsv'){if(!allowed('relatorios'))throw new Error('Acesso restrito.');const d=reportData(),safe=v=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const csv='\uFEFF'+[d.headers,...d.rows].map(r=>r.map(safe).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const el=document.createElement('a');el.href=url;el.download=`realtech-demo-${user.perfil}-${D.today()}.csv`;el.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('CSV do recorte atual exportado.');return;}
 if(a==='resetDemo'){if(user.perfil!=='administrador')throw new Error('Somente Administrador pode reiniciar.');return modal('Reiniciar demonstração',notice('Todos os pedidos e alterações locais serão substituídos pelos três cenários iniciais. Essa ação não pode ser desfeita.','warn'),()=>{const fresh=D.demoSeed();fresh.revision=state.revision+1;localStorage.setItem(KEY,JSON.stringify(fresh));state=fresh;user=state.usuarios[0];storageProblem=false;$('#storageWarning').classList.add('hidden');route='dashboard';selectedId=null;},'Reiniciar dados locais');}
 const confirmations={submitOrder:'Enviar este rascunho ao Financeiro? A edição será bloqueada imediatamente.',approveOrder:'Aprovar comercialmente este pedido?',createOps:'Gerar uma OP independente para cada item deste pedido?',issueSheet:'Gerar o documento operacional com a versão da fórmula preservada?',startOp:'Iniciar a produção desta OP?',payCommission:'Registrar pagamento demonstrativo da comissão?',toggleUser:'Alterar a situação de acesso deste usuário?'};
 if(a==='cancelOrder')return modal('Cancelar pedido',textarea('Justificativa do cancelamento','justificativa','',true),d=>commit(a,{id,...d}),'Cancelar pedido');
 if(confirmations[a])return modal(actionNames[a],notice(confirmations[a]),()=>commit(a,{id}));
 throw new Error('Ação não reconhecida.');
}
function updatePrice(){const el=$('[name="margem"]');if(!el)return;try{const sim=D.priceSimulation(state,find(state.produtos,$('#dialogBody').dataset.product),el.value);$('#priceResult').innerHTML=fields([['Custo por UN',money(sim.custoCentavos)],['Preço de venda',money(sim.precoCentavos)]]);}catch(e){$('#priceResult').innerHTML=notice(esc(e.message),'warn');}}
document.addEventListener('click',e=>{
 const tab=e.target.closest('[data-doc-tab]');if(tab){document.querySelectorAll('[data-doc-tab]').forEach(b=>b.classList.toggle('active',b===tab));document.querySelectorAll('[data-doc-panel]').forEach(p=>p.hidden=p.dataset.docPanel!==tab.dataset.docTab);return;}
 const demo=e.target.closest('[data-demo]');if(demo&&!user){const u=find(state.usuarios,demo.dataset.demo);$('#username').value=u.login;$('#password').value=u.senha;document.querySelectorAll('.profile-choice').forEach(b=>b.classList.toggle('active',b.dataset.demo===u.id));return;}
 const nav=e.target.closest('[data-route]');if(nav&&user){if($('#flowDialog').open)closeModal();go(nav.dataset.route,nav.dataset.id||null);return;}
 const action=e.target.closest('[data-action]');if(!action||!user)return;
 if(action.dataset.action==='removeLine'){action.closest('.order-line').remove();updateOrderTotals();return;}
 try{openAction(action.dataset.action,action.dataset.id);}catch(error){toast(error.message);}
});
function filterOrders(){if(!$('#orderResults'))return;const term=($('#orderSearch').value||'').toLocaleLowerCase('pt-BR'),status=$('[name="filterStatus"]').value;const rows=orders().filter(o=>(!status||o.status===status)&&`${o.numero} ${o.clienteNome} ${D.stage(state,o)}`.toLocaleLowerCase('pt-BR').includes(term));$('#orderResults').innerHTML=table(['Pedido','Cliente','Status','Próxima etapa','Valor','Entrega'],orderRows(rows.slice().reverse()));}
document.addEventListener('input',e=>{
 if(e.target.id==='orderSearch')filterOrders();
 if(e.target.closest('.order-line'))updateOrderTotals();
 if(e.target.name==='margem')updatePrice();
 if(['quantidade','perdasKg','sobrasKg'].includes(e.target.name)&&$('#consumptionRows'))drawConsumption($('#dialogBody').dataset.op);
});
document.addEventListener('change',e=>{if(e.target.name==='filterStatus')filterOrders();if(e.target.name==='clienteId'&&$('#orderLines'))updateOrderTotals();if(e.target.closest('.order-line'))updateOrderTotals();});
