const test = require('node:test')
const assert = require('node:assert/strict')
const D = require('../domain.js')
function sample(kg=100) {
 let s=D.seed()
 const run=(action,payload={})=>{const r=D.execute(s,D.get(s.usuarios,'admin'),action,payload);s=r.state;return r.id}
 const id=run('saveOrder',{modoQuantidade:'KG',tipo:'amostra',clienteId:'c1',itens:[{produtoId:'p1',quantidade:kg}],prazoEntrega:D.day(15)})
 run('createOps',{id})
 return {get s(){return s},run,id,get op(){return s.ordens.find(x=>x.pedidoId===id)}}
}
test('pedido em kg congela base, preço por kg e embalagem; 1 kg cabe em um volume',()=>{
 const h=sample(1),i=D.get(h.s.pedidos,h.id).itens[0],p=D.get(h.s.produtos,'p1')
 assert.equal(i.unidade,'KG');assert.equal(i.pesoKg,1);assert.equal(i.pesoEmbalagemKg,5)
 assert.equal(i.precoCentavos,p.precoCentavos/5);assert.equal(D.packageCount(i),1);assert.equal(D.volumeCount(i),1)
 assert.equal(h.op.quantidadePrevista*h.op.pesoKg,1)
 assert.doesNotMatch(i.nome,/5\s*kg/i)
})
test('100 kg: máximo 50 dá duas batidas, três batidas fecham totais sem mudar fórmula',()=>{
 const h=sample(),before=JSON.stringify(h.op.formula)
 assert.equal(D.batchPlan(h.op).quantidade,2)
 h.run('issueSheet',{id:h.op.id})
 h.run('modifyBatches',{id:h.op.id,maximoKg:100/3,quantidadeBatidas:3})
 assert.equal(h.op.documentoOp.revisaoPlanejamento,1)
 const plan=h.op.documentoOp.batidas,rows=D.productionFormulaRows(h.op,plan)
 assert.equal(plan.quantidade,3);assert.equal(plan.totalKg,100)
 for(const [field,total] of [['percentual',100],['totalKg',100],['batidaKg',33.33333]]) assert.ok(Math.abs(rows.reduce((n,r)=>n+r[field],0)-total)<0.000001)
 assert.equal(JSON.stringify(h.op.formula),before)
 assert.throws(()=>h.run('modifyBatches',{id:h.op.id,maximoKg:20,quantidadeBatidas:2}),/excede/)
 assert.throws(()=>D.batchPlan(h.op,50,1.5),/inteiras/)
 h.run('startOp',{id:h.op.id})
 h.run('modifyBatches',{id:h.op.id,maximoKg:50,quantidadeBatidas:2})
 assert.equal(h.op.documentoOp.batidas.kgPorBatida,50)
 assert.equal(h.op.status,'emProducao')
})
test('amostra fracionada aponta e estoca em kg, consumindo a massa real',()=>{
 const h=sample(1.25)
 h.run('issueSheet',{id:h.op.id});h.run('startOp',{id:h.op.id})
 h.run('reportProduction',{id:h.op.id,quantidade:1.25,perdasKg:0,sobrasKg:0,validade:D.day(180),consumos:D.suggestConsumption(h.s,h.op,1.25)})
 assert.equal(h.op.quantidadeProduzida,1.25)
 const lot=h.s.lotes.find(x=>x.opId===h.op.id&&x.tipo==='produto')
 assert.equal(lot.unidade,'KG');assert.equal(lot.saldo,1.25)
})
test('data compacta e histórico em unidades continuam explícitos',()=>{
 assert.equal(D.compactLotDate('2026-10-05'),'05102026')
 const s=D.demoSeed(),historical=s.pedidos.find(x=>x.itens.some(i=>i.unidade==='UN'))
 assert.ok(historical)
 const i=historical.itens[0];assert.equal(D.packageCount(i),i.quantidade)
})

test('replanejar após apontamento preserva consumos, lotes e produção e bloqueia OP concluída',()=>{
 const h=sample(2)
 h.run('issueSheet',{id:h.op.id});h.run('startOp',{id:h.op.id})
 const report=()=>h.run('reportProduction',{id:h.op.id,quantidade:1,perdasKg:0,sobrasKg:0,validade:D.day(180),consumos:D.suggestConsumption(h.s,h.op,1)})
 report()
 const stock=JSON.stringify(h.s.lotes),records=JSON.stringify(h.op.apontamentos),formula=JSON.stringify(h.op.formula)
 h.run('modifyBatches',{id:h.op.id,maximoKg:1,quantidadeBatidas:2})
 assert.equal(h.op.quantidadeProduzida,1)
 assert.equal(JSON.stringify(h.s.lotes),stock)
 assert.equal(JSON.stringify(h.op.apontamentos),records)
 assert.equal(JSON.stringify(h.op.formula),formula)
 assert.equal(h.op.documentoOp.batidas.kgPorBatida,1)
 report()
 assert.throws(()=>h.run('modifyBatches',{id:h.op.id,maximoKg:1,quantidadeBatidas:2}),/OP aberta/)
})
